/* Writes the two places the item bank has to appear, from the one place it is
 * written: sql/025-disc.sql, which scores the answers, and the block of markup
 * in careers.html that asks the questions.
 *
 * Generated rather than typed twice because the failure mode of typing it
 * twice is silent. If the page and the scoring map disagree about which word
 * is a D, nothing errors -- every applicant just gets a slightly wrong
 * profile, and nobody ever finds out.
 *
 * Run: node tools/build-disc.mjs   (tools/check.mjs re-runs it and diffs) */
import { readFileSync, writeFileSync } from "node:fs";
import { GROUPS, STYLES, LETTERS } from "./disc-items.mjs";

const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

/* ── the questions ─────────────────────────────────────────────────────────
   A row per word, with a Most column and a Least column. Two radio groups per
   question, which is what makes it forced choice: the browser will not let a
   second word be marked Most, so somebody who is all four things has to
   decide which one they are more. */
export function markup() {
  const rows = GROUPS.map((g, gi) => {
    const words = g.map(([word], wi) =>
      '            <div class="disc__w">' +
              '<span class="disc__t">' + esc(word) + "</span>" +
              '<label class="disc__p"><input type="radio" name="disc_m' + gi + '" value="' + wi +
                '" aria-label="' + esc(word) + ' — most like me"><span class="disc__dot"></span></label>' +
              '<label class="disc__p"><input type="radio" name="disc_l' + gi + '" value="' + wi +
                '" aria-label="' + esc(word) + ' — least like me"><span class="disc__dot disc__dot--l"></span></label>' +
            "</div>"
    ).join("\n");

    return (
      '        <fieldset class="disc__g" data-disc-g="' + gi + '">\n' +
      '          <legend class="disc__n">' + (gi + 1) + " of " + GROUPS.length + "</legend>\n" +
      '          <div class="disc__hd"><span></span><span>Most</span><span>Least</span></div>\n' +
      '          <div class="disc__ws">\n' + words + "\n          </div>\n" +
      '          <p class="err disc__e" data-disc-err="' + gi + '" aria-live="polite"></p>\n' +
      "        </fieldset>"
    );
  }).join("\n");

  return "\n" + rows + "\n";
}

/* Emitted as the same nested array the page renders from, so a reviewer can
   line the two up by eye. The page itself never receives it. */
function sqlMap() {
  return GROUPS.map((g) => "[" + g.map(([, k]) => '"' + k + '"').join(",") + "]").join(",\n     ");
}

const D = "$";  /* keeps dollar-quoted SQL bodies out of this file's own templates */

export const sql = `-- 025 — the DISC questionnaire
--
-- Run after: 024
-- Safe to re-run: yes
-- Also needed: nothing in the dashboard.
--
-- GENERATED by tools/build-disc.mjs from tools/disc-items.mjs. Edit the item
-- bank and re-run; edits made here are overwritten.
--
-- Twelve groups of four words. The applicant marks one word in each group as
-- most like them and one as least like them, and the difference between the
-- two counts, per letter, is the profile.

create table if not exists public.application_disc (
  application_id  uuid primary key references public.applications (id) on delete cascade,

  -- What was actually ticked: [{"g":0,"m":1,"l":3}, ...]. Positions, not
  -- letters, because the browser is never told which word is a D.
  answers         jsonb not null,

  -- Filled in by the trigger below. Range -12 to 12.
  d               smallint,
  i               smallint,
  s               smallint,
  c               smallint,
  primary_style   text,
  secondary_style text,

  taken_at        timestamptz not null default now(),

  constraint application_disc_style_known check (
    coalesce(primary_style, 'D') in ('D', 'I', 'S', 'C') and
    coalesce(secondary_style, 'D') in ('D', 'I', 'S', 'C')
  )
);

alter table public.application_disc enable row level security;
revoke all on public.application_disc from anon, authenticated;

-- ==========================================================================
-- THE APPLICANT SENDS ANSWERS, NOT A SCORE
-- ==========================================================================
--
-- anon may write two columns and no others. A column-level grant refuses the
-- whole statement over a single column it does not cover, so a page that tried
-- to send its own d/i/s/c would not get a wrong score stored — it would get a
-- 42501 and store nothing at all. That is the intent, not a side effect.

grant insert (application_id, answers) on public.application_disc to anon;
grant select (application_id, answers, d, i, s, c, primary_style, secondary_style, taken_at)
  on public.application_disc to authenticated;

drop policy if exists "public can take the questionnaire" on public.application_disc;
create policy "public can take the questionnaire"
  on public.application_disc for insert to anon with check (true);

drop policy if exists "see the profile if you may see the applicant" on public.application_disc;
create policy "see the profile if you may see the applicant"
  on public.application_disc for select to authenticated
  using (
    public.has_permission('applications.view_all')
    or exists (
      select 1 from public.applications a
      where a.id = application_id
        and (a.user_id = auth.uid()
             or lower(a.email) = lower(coalesce(auth.jwt() ->> 'email', '__nobody__')))
    )
  );

-- No update and no delete for anybody, staff included. A personality answer is
-- not something anyone should be able to nudge after an interview went badly.

-- --------------------------------------------------------------------------
-- Scoring
-- --------------------------------------------------------------------------
--
-- The map lives here and nowhere the browser can read it. The page sends the
-- positions it ticked; this turns positions into letters and counts them.
--
-- Ties break D, I, S, C. An arbitrary order, but a fixed one — the same
-- answers have to produce the same profile every time, or two people reading
-- the same applicant see two different things.

create or replace function public.score_disc()
returns trigger
language plpgsql
as ${D}fn${D}
declare
  map    jsonb := '[
     ${sqlMap()}
  ]'::jsonb;
  a      jsonb;
  g      int;
  m      int;
  l      int;
  seen   int[] := '{}';
  tally  jsonb := '{"D":0,"I":0,"S":0,"C":0}'::jsonb;
  k      text;
  ranked text[];
begin
  if jsonb_typeof(new.answers) <> 'array' then
    raise exception 'answers must be an array';
  end if;
  if jsonb_array_length(new.answers) <> jsonb_array_length(map) then
    raise exception 'answers must cover all % groups, got %',
      jsonb_array_length(map), jsonb_array_length(new.answers);
  end if;

  for a in select * from jsonb_array_elements(new.answers) loop
    g := (a ->> 'g')::int;
    m := (a ->> 'm')::int;
    l := (a ->> 'l')::int;

    if g is null or m is null or l is null then
      raise exception 'every answer needs g, m and l';
    end if;
    if g < 0 or g >= jsonb_array_length(map) then
      raise exception 'group % is not one of the questions', g;
    end if;
    if m < 0 or m > 3 or l < 0 or l > 3 then
      raise exception 'a pick must be 0 to 3';
    end if;
    if m = l then
      raise exception 'group % marks the same word most and least', g;
    end if;
    if g = any (seen) then
      raise exception 'group % answered twice', g;
    end if;
    seen := seen || g;

    k := map -> g ->> m;
    tally := jsonb_set(tally, array[k], to_jsonb(((tally ->> k)::int) + 1));
    k := map -> g ->> l;
    tally := jsonb_set(tally, array[k], to_jsonb(((tally ->> k)::int) - 1));
  end loop;

  new.d := (tally ->> 'D')::int;
  new.i := (tally ->> 'I')::int;
  new.s := (tally ->> 'S')::int;
  new.c := (tally ->> 'C')::int;

  select array_agg(letter order by score desc, ord)
    into ranked
    from (values ('D', new.d, 1), ('I', new.i, 2), ('S', new.s, 3), ('C', new.c, 4))
      as t (letter, score, ord);

  new.primary_style   := ranked[1];
  new.secondary_style := ranked[2];
  new.taken_at        := now();
  return new;
end;
${D}fn${D};

drop trigger if exists application_disc_score on public.application_disc;
create trigger application_disc_score
  before insert on public.application_disc
  for each row execute function public.score_disc();

-- --------------------------------------------------------------------------
-- Reading it
-- --------------------------------------------------------------------------
--
-- The admin page joins this on, so it wants the letter already spelled out.

drop view if exists public.application_disc_read;
create view public.application_disc_read
with (security_invoker = true) as
  select application_id,
         d, i, s, c,
         primary_style,
         secondary_style,
         case primary_style
${LETTERS.map((k) => `           when '${k}' then '${STYLES[k].name}'`).join("\n")}
         end as primary_name,
         taken_at
  from public.application_disc;

grant select on public.application_disc_read to authenticated;

-- ==========================================================================
-- Check it worked
-- ==========================================================================
--
-- anon writes two columns and reads none. If a score column ever turns up in
-- the anon row, the page can send its own answer to the personality test.

select grantee,
       string_agg(distinct privilege_type, ',' order by privilege_type) as privileges,
       string_agg(distinct column_name, ',' order by column_name) as columns
from information_schema.column_privileges
where table_name = 'application_disc' and grantee in ('anon', 'authenticated')
group by grantee;

-- Insert and select only. If update or delete ever shows up here, somebody can
-- change an applicant's answers after meeting them.
select coalesce(string_agg(distinct p.polcmd::text, ','), 'none') as commands
from pg_class c
left join pg_policy p on p.polrelid = c.oid
where c.relname = 'application_disc';

-- The scorer, run on a sheet nobody filled in. Marking word 0 most and word 1
-- least in every group has to come back with the four letters summing to zero,
-- because each group adds a point to one letter and takes one from another. If
-- this raises, the trigger is wrong and nobody should be asked to take it.
--
-- The whole thing happens inside a block that always throws, so the rows never
-- exist outside it. Deleting them afterwards would have worked too, right up
-- until an assertion failed and left a fake applicant in the table with
-- everybody's real ones. plpgsql variables survive the rollback; rows do not,
-- which is why the message is built before the throw and printed after it.

do ${D}t${D}
declare
  probe jsonb;
  ghost uuid;
  got   record;
  msg   text;
begin
  begin
    select jsonb_agg(jsonb_build_object('g', n, 'm', 0, 'l', 1))
      into probe
      from generate_series(0, ${GROUPS.length - 1}) as n;

    insert into public.applications (name, email, country)
      values ('disc self-test', 'disc-self-test@invalid', 'nowhere')
      returning id into ghost;

    insert into public.application_disc (application_id, answers)
      values (ghost, probe);

    select d, i, s, c, primary_style into got
      from public.application_disc where application_id = ghost;

    if got.d + got.i + got.s + got.c <> 0 then
      raise exception 'scorer is wrong: % + % + % + % does not sum to zero',
        got.d, got.i, got.s, got.c;
    end if;

    msg := format('scorer ok — %s groups, sample profile %s (D %s, I %s, S %s, C %s)',
      ${GROUPS.length}, got.primary_style, got.d, got.i, got.s, got.c);

    raise exception 'disc-self-test-rollback';
  exception
    when others then
      if sqlerrm <> 'disc-self-test-rollback' then raise; end if;
  end;

  raise notice '%', msg;
end
${D}t${D};
`;

/* Both outputs as strings, so a test can ask whether the files on disk still
   match the item bank without rewriting them to find out. A staleness check
   that fixes the staleness passes on its second run and tells you nothing. */
export const sqlText = () => sql.replace(/\r?\n/g, "\r\n");

export function pageText(page) {
  const START = "<!-- disc:start -->";
  const END = "<!-- disc:end -->";
  const a = page.indexOf(START);
  const b = page.indexOf(END);
  if (a < 0 || b < 0) throw new Error("careers.html has no disc:start / disc:end markers");
  const nl = page.includes("\r\n") ? "\r\n" : "\n";
  return page.slice(0, a + START.length) + markup().replace(/\n/g, nl) + page.slice(b);
}

/* Only writes when run as a command. Imported, it is just the two strings. */
if (process.argv[1] && process.argv[1].replace(/\\/g, "/").endsWith("tools/build-disc.mjs")) {
  writeFileSync("sql/025-disc.sql", sqlText());
  writeFileSync("careers.html", pageText(readFileSync("careers.html", "utf8")));
  console.log("disc: " + GROUPS.length + " groups -> sql/025-disc.sql, careers.html");
}
