-- 063 — the verdict does not wait for a person

-- Run after: 049 (the scorer this replaces), 050
-- Safe to re-run: yes
-- Also needed: nothing in the dashboard.
--
-- ==========================================================================
-- WHAT THIS CHANGES, IN ONE LINE
-- ==========================================================================
--
-- An assessment is graded the moment she sends it, by machine, with nobody in
-- the way. Asked for deliberately, and this file is the honest account of what
-- was traded for it.
--
-- ==========================================================================
-- WHAT WAS THERE BEFORE, AND WHY
-- ==========================================================================
--
-- 049 ended with:
--
--     if not checked or not marked then
--       new.verdict := 'in_progress';
--
-- checked means somebody read her typing proof and wrote down what it said.
-- marked means somebody read her written reply and scored it. Until both had
-- happened the row sat at 'in_progress' — not a failure, and it declined
-- nobody; it was the row saying it was waiting on us rather than on her.
--
-- That gate exists because of a real incident, recorded in 048: score_typing
-- is worked out from typing_wpm and typing_accuracy, both of those columns are
-- granted to the applicant because the page has to write them, and anybody who
-- can open a browser console can send whatever numbers they like. On the Admin
-- Tasks track both gated axes read from the typing figure, so an invented
-- number produced a verdict of 'passed' on its own.
--
-- ==========================================================================
-- SO BE PLAIN ABOUT WHAT THIS FILE GIVES BACK
-- ==========================================================================
--
-- The typing figure now reaches a verdict without anybody looking at it. Since
-- e122503 that figure is a number she reads off typingtest.com and types in
-- herself, with a screenshot attached as proof — and the screenshot is not
-- read by anything. It is filed, and it is opened only if somebody chooses to.
--
-- There is no version of this that is both automatic and sound. The database
-- cannot tell a measured number from an invented one, because both arrive from
-- her browser through the same grant. Automatic means accepting a number she
-- supplied. That is the trade, it was made knowingly, and writing it down here
-- is the only honest part available.
--
-- Three things make it survivable, and none of them is this file:
--
--   1. The move to Interview still is not automatic — see below. A machine
--      verdict no longer emails a stranger.
--   2. typing_verified_wpm still overrules the claim wherever somebody fills
--      it in, and the row re-scores when they do.
--   3. The interview is the real check, and always was. A number is a filter.
--
-- ==========================================================================
-- WHAT IS NOT CHANGING
-- ==========================================================================
--
-- The scorer below is 049's, copied whole, with the four lines of the gate
-- replaced. The judgement key inside it is generated by
-- tools/assessment-items.mjs and tools/check.mjs fails the build if the two
-- ever disagree, so it is carried across rather than retyped.

do $pre$
begin
  if to_regclass('public.application_assessment') is null then
    raise exception
      'sql/045 has not been run on this database. It creates the assessment table that this file changes. Run sql/045-the-assessment.sql first, then this one.';
  end if;
end
$pre$;

create or replace function public.score_assessment()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare
  q        integer;
  key      integer[];
  picked   integer;
  got      integer;
  possible integer;
  axes     text[];
  eng      integer;
  cust     integer;
  det      integer;
  sal      integer;
  ok       boolean := true;
  wpm      integer;
  acc      integer;
  marked   boolean;
begin
  if new.submitted_at is null then
    return new;
  end if;

  -- Score on the send, and again whenever a person writes down something the
  -- verdict depends on: what the typing proof said, or what the writing was
  -- worth. Any other update leaves every number exactly as it was found.
  if old.submitted_at is not null
     and new.typing_verified_wpm is not distinct from old.typing_verified_wpm
     and new.typing_verified_accuracy is not distinct from old.typing_verified_accuracy
     and new.written_score is not distinct from old.written_score then
    return new;
  end if;

  -- ── the judgement scenarios ────────────────────────────────────────────
  -- generated by tools/assessment-items.mjs — do not edit by hand
  got := 0; possible := 0;
  for q, key in
    select * from (values
      (0,  array[2, 0, 0, 1]),
      (1,  array[0, 1, 0, 2]),
      (2,  array[0, 1, 2, 0]),
      (3,  array[1, 2, 0, 0]),
      (4,  array[0, 1, 0, 2]),
      (5,  array[2, 0, 1, 0]),
      (6,  array[1, 2, 0, 0]),
      (7,  array[0, 0, 2, 2]),
      (8,  array[0, 1, 2, 0]),
      (9,  array[0, 0, 0, 2]),
      (10, array[2, 0, 0, 1]),
      (11, array[1, 2, 0, 0])
    ) as t(q, pts)
  loop
    possible := possible + 2;
    picked := nullif(new.scenario_answers -> q ->> 'p', '')::integer;
    if picked is not null and picked between 0 and 3 then
      got := got + key[picked + 1];
    end if;
  end loop;
  new.score_scenarios := case when possible = 0 then 0
                              else round((got::numeric / possible) * 10) end;

  -- ── english ────────────────────────────────────────────────────────────
  -- generated by tools/assessment-items.mjs — do not edit by hand
  got := 0; possible := 0;
  for q, key in
    select * from (values
      (0, array[2, 0, 0, 1]),
      (1, array[0, 2, 0, 1]),
      (2, array[0, 1, 0, 2]),
      (3, array[0, 2, 1, 0]),
      (4, array[2, 0, 0, 1]),
      (5, array[0, 1, 2, 0]),
      (6, array[0, 0, 2, 1]),
      (7, array[1, 0, 0, 2])
    ) as t(q, pts)
  loop
    possible := possible + 2;
    picked := nullif(new.english_answers -> q ->> 'p', '')::integer;
    if picked is not null and picked between 0 and 3 then
      got := got + key[picked + 1];
    end if;
  end loop;
  new.score_english := case when possible = 0 then 0
                            else round((got::numeric / possible) * 10) end;

  -- ── detail ─────────────────────────────────────────────────────────────
  -- generated by tools/assessment-items.mjs — do not edit by hand
  got := 0; possible := 0;
  for q, key in
    select * from (values
      (0, array[2, 0, 0, 0]),
      (1, array[0, 2, 0, 0]),
      (2, array[0, 0, 2, 0]),
      (3, array[0, 0, 2, 0]),
      (4, array[0, 0, 0, 2]),
      (5, array[2, 0, 0, 1]),
      (6, array[0, 0, 0, 2]),
      (7, array[1, 2, 0, 0])
    ) as t(q, pts)
  loop
    possible := possible + 2;
    picked := nullif(new.detail_answers -> q ->> 'p', '')::integer;
    if picked is not null and picked between 0 and 3 then
      got := got + key[picked + 1];
    end if;
  end loop;
  new.score_detail := case when possible = 0 then 0
                           else round((got::numeric / possible) * 10) end;

  -- ── sales ──────────────────────────────────────────────────────────────
  -- Only the sales track is asked these, so an empty bank is an ordinary
  -- state rather than a zero somebody earned. It scores 0 and gates nothing,
  -- because sales is not in any other track's axes.
  -- generated by tools/assessment-items.mjs — do not edit by hand
  got := 0; possible := 0;
  for q, key in
    select * from (values
      (0, array[0, 2, 1, 0]),
      (1, array[2, 0, 0, 1]),
      (2, array[0, 0, 2, 0]),
      (3, array[2, 0, 0, 1]),
      (4, array[0, 0, 1, 2]),
      (5, array[0, 0, 2, 1]),
      (6, array[0, 2, 0, 1]),
      (7, array[0, 0, 0, 2])
    ) as t(q, pts)
  loop
    possible := possible + 2;
    picked := nullif(new.sales_answers -> q ->> 'p', '')::integer;
    if picked is not null and picked between 0 and 3 then
      got := got + key[picked + 1];
    end if;
  end loop;
  new.score_sales := case when possible = 0 then 0
                          else round((got::numeric / possible) * 10) end;

  -- ── typing ─────────────────────────────────────────────────────────────
  -- Still recorded, no longer standing in for anything. The checked figure
  -- wins where there is one.
  --
  -- 049 also set a `checked` flag here and the verdict below read it. Nothing
  -- reads it now, so it is gone rather than left sitting there looking load
  -- bearing. The question it asked — has anybody actually looked at this
  -- number — did not stop mattering; it moved to advance_on_assessment, which
  -- is the one step where the answer still changes what happens.
  wpm := coalesce(new.typing_verified_wpm, new.typing_wpm, 0);
  acc := coalesce(new.typing_verified_accuracy, new.typing_accuracy, 0);

  if acc < 95 then
    new.score_typing := least(4, greatest(0, round(wpm::numeric / 20)));
  else
    new.score_typing := least(10, greatest(0, round(wpm::numeric / 6)));
  end if;

  -- ── the four axes ──────────────────────────────────────────────────────
  --
  -- english is the average of the two things that measure it: eight items a
  -- machine marks, and a person reading a real reply to a real customer. They
  -- disagree sometimes, and when they do the average is a better answer than
  -- either — which is the entire argument for having both.
  marked := new.written_score is not null;

  eng  := case when marked
               then round((coalesce(new.score_english, 0) + new.written_score)::numeric / 2)
               else coalesce(new.score_english, 0) end;
  cust := coalesce(new.score_scenarios, 0);
  det  := coalesce(new.score_detail, 0);
  sal  := coalesce(new.score_sales, 0);

  axes := case new.track
            when 'Admin Tasks'       then array['english', 'detail']
            when 'Sales & Marketing' then array['english', 'sales', 'customer']
            else array['english', 'customer']
          end;

  if 'english'  = any(axes) and eng  < 7 then ok := false; end if;
  if 'customer' = any(axes) and cust < 7 then ok := false; end if;
  if 'detail'   = any(axes) and det  < 7 then ok := false; end if;
  if 'sales'    = any(axes) and sal  < 7 then ok := false; end if;

  -- Typing is a floor rather than an axis. 40 wpm is the BPO floor and 95% the
  -- accuracy line; below either, the work comes back for somebody to redo.
  if wpm < 40 or acc < 95 then ok := false; end if;

  -- ── the verdict ────────────────────────────────────────────────────────
  --
  -- The gate that used to stand here is gone, and this is the whole file.
  --
  -- It read: if not checked or not marked then 'in_progress'. Both halves were
  -- right about evidence and both cost the same thing — every assessment,
  -- however obviously it passed or failed on the parts a machine marks, sat
  -- waiting on a person before it would say anything at all.
  --
  -- Both human figures still change the numbers where they exist: the verified
  -- typing figure wins over the claimed one, and a marked written reply is
  -- still half the english axis. What changes is that their ABSENCE no longer
  -- suppresses the answer. They are corrections now rather than preconditions,
  -- and the early return at the top of this function already re-scores the row
  -- the moment either of them arrives.
  new.verdict := case when ok then 'passed' else 'below_line' end;

  return new;
end
$fn$;

revoke all on function public.score_assessment() from public, anon, authenticated;

drop trigger if exists assessment_scored on public.application_assessment;
create trigger assessment_scored
  before update on public.application_assessment
  for each row execute function public.score_assessment();

-- ==========================================================================
-- THE ONE GATE THAT STAYS
-- ==========================================================================
--
-- 045's advance_on_assessment moves her to 'interview' the moment the verdict
-- turns 'passed', and setting applications.status fires the mail from 031. So
-- before this file, a pass meant an email — and a pass required two people, so
-- an email required two people.
--
-- Grading automatically removes those two people. Left alone, this trigger
-- would therefore send an interview invitation to a stranger on the strength
-- of a number she typed into a box about herself, with nothing between the two
-- events. That is not a grading decision, it is an outward-facing one, and it
-- is not what was asked for.
--
-- So the verdict is automatic and the invitation is not. She is graded on the
-- spot; moving her to Interview waits until somebody has read the typing
-- proof, which is one glance at a screenshot on a row that already says
-- 'passed' in front of them.
--
-- To make that automatic too, delete the typing_verified_wpm condition below
-- and re-run this file. It is deliberately the only thing standing there, so
-- that removing it is one line and an act of intent rather than a side effect.

create or replace function public.advance_on_assessment()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
begin
  if new.verdict <> 'passed' or old.verdict = 'passed' then
    return new;
  end if;

  -- The gate that used to live in the scorer, kept for this one step only:
  -- an email to somebody who has not been read by anybody is the part of the
  -- old rule worth keeping.
  if new.typing_verified_wpm is null and new.typing_verified_accuracy is null then
    return new;
  end if;

  -- Only from assessment. Somebody already at interview or hired must not be
  -- walked backwards or forwards by a re-sit.
  update public.applications
     set status = 'interview',
         status_changed_at = now()
   where id = new.application_id
     and status = 'assessment';

  return new;
end
$fn$;

revoke all on function public.advance_on_assessment() from public, anon, authenticated;

drop trigger if exists assessment_advances on public.application_assessment;
create trigger assessment_advances
  after update on public.application_assessment
  for each row execute function public.advance_on_assessment();

-- ==========================================================================
-- WHAT TO LOOK AT AFTERWARDS
-- ==========================================================================
--
-- 049 ends with two queries to run by hand, and both mean something different
-- now.
--
-- The first lists what is still waiting on a person. It is now the spot-check
-- queue: every row in it already has a verdict, and what it has not got is
-- anybody's word for the number behind it. It is also now the list of people
-- who are graded but not yet invited, because of the gate above.
--
-- The second asks which columns the applicant may write:
--
--   select column_name, privilege_type
--   from information_schema.column_privileges
--   where table_name = 'application_assessment'
--     and grantee = 'authenticated'
--     and privilege_type = 'UPDATE'
--   order by column_name;
--
-- 049's comment on it says none of the score_ columns may appear. That is the
-- right rule and it is not the whole one. 048 granted
--
--   grant update (typing_verified_wpm, typing_verified_accuracy)
--     on public.application_assessment to authenticated;
--
-- and a signed-in applicant IS authenticated. RLS fences rows, not columns —
-- 045's applicant policy is `owns_application(...) and submitted_at is null`,
-- which says nothing about which columns — so on these files as written she
-- can write her own verified pair while her row is unsent, and then send it.
--
-- That was survivable while the verdict waited for a person, because the
-- person was the thing being waited for either way. THIS FILE REMOVES THAT
-- WAIT. If the grant is real on the live database, the gate above is the only
-- thing left between a self-scored row and an interview invitation, and it is
-- reading a column she may be able to fill in herself.
--
-- So run that query. If typing_verified_wpm or typing_verified_accuracy comes
-- back in the list, the fix is one statement and it belongs before this file
-- is trusted:
--
--   revoke update (typing_verified_wpm, typing_verified_accuracy)
--     on public.application_assessment from authenticated;
--
-- and then a grant to whatever role staff hold, rather than to the role
-- everybody holds. This file does not do it, because it has not been confirmed
-- against the live database and a revoke aimed at the wrong role would lock
-- the people who check proofs out of the column they check them into.

insert into public.schema_migrations (n) values (63) on conflict (n) do nothing;
